# NOTE: we set/switch image repository related to change in bitnami to remove the original bitnami org/repository dockerhub repos and migrate all existing/old images to bitnamilegacy, for more info check https://github.com/bitnami/containers/issues/83267
# TODO: consider a change to use another image repository which is maintained
global:
  security:
    allowInsecureImages: true
image:
  repository: bitnamilegacy/metrics-server

extraArgs:
  - --kubelet-insecure-tls

apiService:
  ## Specifies whether the v1beta1.metrics.k8s.io API service should be created
  ## This should not be necessary in k8s version >= 1.8, but depends on vendors and cloud providers.
  ##
  create: true
